### ISSUE TITLE
Publishing: submit both backstage plugins to the Backstage Plugin Directory

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/backstage-plugins#35]
We should submit both of our Backstage plugins to the Backstage Plugin Directory so that users can more easily find our tools.

Steps for submitting are outlined here: https://backstage.io/docs/plugins/add-to-directory/

## Changes left to make (after name change discussion)
- [x] Make new PR in the Coder plugins repo to update the name of the frontend devcontainers plugin, and make sure that things are being published under the correct name
- [x] Update the PR opened with Spotify, and update the link for the devcontainers plugin
- [x] Update our README to reflect our status as an official Backstage plugin

**Comment by Parkreiner** [comment]
Going to put the badges stuff on hold until I get this done

**Comment by Kira-Pilot** [comment]
@bpmct @kylecarbs regarding naming: we have decided to keep the `-backend` suffix for the backend plugin and have no suffix for the  frontend plugin. This follows the convention [set by Backstage](https://github.com/backstage/backstage/tree/master/plugins).

**Comment by Parkreiner** [comment]
Actually, I'm starting to wonder if we should stick with the `-react` suffix. Took me a while to track this down, but there is [a piece of documentation that describes what each suffix means internally](https://backstage.io/docs/architecture-decisions/adrs-adr011/#decision)

The `-react` suffix means:
> `x-react`: Contains shared widgets, hooks and similar that both the plugin itself (`x`) and third-party frontend plugins can depend on.

Since we're not necessarily publishing a full-page plugin, but are instead giving people access to hooks and smaller components that they can bring into their own plugins, I feel like the suffix makes sense

**Comment by kylecarbs** [comment]
Not a biggie to me. If it's accepted in the community, it's good with me.

**Comment by Parkreiner** [comment]
Wanted to give an update: it sounds like the core Backstage contributors think we're good with the current names.

We need two approvals to merge the changes in, though. We have one, but are waiting for another. I just asked whether there was anything else I need to do to get that last approval

**Comment by Parkreiner** [comment]
As of today, we are on the Backstage plugins page. Closing this out.

**Comment by Parkreiner** [comment]
Oh, actually, forgot one thing – updating the READMEs to indicate that we're official
